language: generic

sudo: required
services:
  - docker

before_installL:
  - docker build -t whalecaptain/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true whalecaptain/docker-react npm run test